[repository]
name = "hyprPluginMaster"
authors = ["3L0C"]

[hyprPluginMaster]
description = "Hyprland Master Layout Plugin - A plugin version of Hyprland's master layout"
authors = ["3L0C"]
output = "masterLayoutPlugin.so"
build = [
    "make"
]
